---
title: "Time Series Analysis"
author: 
- "Fynn Hayton-Ruffner"
- "Shekinah Ninziza"
- "Kinglee Tham"
---

```{r}
#| include: false

# Packages
library(ggplot2)
library(tidytext)
library(tidyverse)
library(RColorBrewer)
library(ggthemes)
library(textdata)
library(lubridate)
library(viridis)
library(ggiraph)

# Data 
load('./data/sentiment_posts_quarterly.Rdata')
load('./data/keyword_posts_quarterly.Rdata')

```

```{r}
# Over time analysis for QUARTERLY sentiment average per subreddit
gg_sentiment_quarterly <- ggplot(data = sentiment_posts_quarterly) +
  geom_point_interactive(aes(x = quarter, 
                            y = avg_sentiment, 
                            tooltip = avg_sentiment)) + 
  geom_line(aes(x = quarter, 
                y = avg_sentiment)) +
  facet_wrap(~subreddit, scales = "free", ncol=1) +
  labs(
    x = 'Date',
    y = 'Quarterly Average Sentiment Score') +
  theme_minimal() 

girafe(ggobj = gg_sentiment_quarterly)
```

```{r}
# Over time analysis for QUARTERLY comment average per subreddit
gg_point_comments_quarterly <- ggplot(data = sentiment_posts_quarterly) +
  geom_point_interactive(aes(x = quarter, 
                            y = avg_comments, 
                            tooltip = avg_comments)) + 
  geom_line(aes(x = quarter, 
                y = avg_comments)) +
  facet_wrap(~subreddit, scales = "fixed", ncol=1) +
  labs(
    x = 'Date',
    y = 'Quarterly Average Comments') +
  theme_minimal() 

girafe(ggobj = gg_point_comments_quarterly)
```

```{r}
# Over time analysis for QUARTERLY admissions keywords per subreddit

gg_point_keywords_quarterly <- ggplot(data = keyword_posts_quarterly) +
  geom_point_interactive(aes(x = quarter, 
                             y = avg_keywords, 
                             tooltip = avg_keywords)) + 
  geom_line(aes(x = quarter, 
                y = avg_keywords)) +
  facet_wrap(~subreddit, scales = "fixed", ncol=1) +
  scale_x_date(
    date_breaks  = "1 year", # one tick on the x per year
    date_labels  = "%Y" # just showing the year, not month or days
  ) +
  labs(
    x = 'Date',
    y = 'Quarterly Average Keywords per Post'
  ) +
  theme_minimal() 

girafe(ggobj = gg_point_keywords_quarterly)
```

